[phases.setup]
nixPkgs = ["...", "dotnet-sdk_8"]

[phases.build]
cmds = ["cd WorshipPlannerBot.Api && dotnet restore", "cd WorshipPlannerBot.Api && dotnet build -c Release"]

[start]
cmd = "cd WorshipPlannerBot.Api && dotnet run --urls http://0.0.0.0:$PORT"